name: translocale_dartnative_example
description: English, French, and Arabic localization with optional TransLocale delivery.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.12.0-192.0.dev <4.0.0'
dependencies:
  dartnative: ^1.0.0
  dartnative_ios: ^1.0.0
  dartnative_android: ^1.0.0
  dartnative_system: ^1.0.0
  dartnative_path_provider: ^1.0.0
  translocale_dartnative:
    path: ../
dev_dependencies:
  lints: ^5.1.1
