import 'dart:convert';
import 'dart:io';
import 'catalog.dart';

String _quote(String value) => jsonEncode(value).replaceAll(r'$', r'\$');

/// Read ARB files and produce a Dart bundle without cloud requests or credentials.
/// All files must be regular files. Existing output is preserved unless it is
/// this generator's output and the caller explicitly passes replace.
String generateBundle({
  required String directory,
  required String sourceLocale,
  required String catalog,
  required String output,
  bool check = false,
  bool replace = false,
}) {
  final dir = Directory(directory);
  final files = dir.listSync().where((f) => f.path.endsWith('.arb')).toList()
    ..sort((a, b) => a.path.compareTo(b.path));
  if (files.isEmpty || files.length > 11) {
    throw FormatException('Use 1–11 ARB files.');
  }
  final messages = <String, Map<String, String>>{};
  for (final entity in files) {
    if (FileSystemEntity.typeSync(entity.path, followLinks: false) !=
        FileSystemEntityType.file) {
      throw FormatException(
        'ARB inputs must be regular files, not symbolic links.',
      );
    }
    final file = File(entity.path);
    if (file.lengthSync() > 100000) {
      throw FormatException('ARB inputs must be at most 100 KB.');
    }
    final json = jsonDecode(file.readAsStringSync());
    if (json is! Map<String, dynamic> || json['@@locale'] is! String) {
      throw FormatException('Every ARB file needs an @@locale string.');
    }
    final locale = canonicalLocale(json['@@locale'] as String);
    if (messages.containsKey(locale)) {
      throw FormatException('Duplicate locale: $locale.');
    }
    final entries = <String, String>{};
    for (final entry in json.entries) {
      if (entry.key.startsWith('@')) continue;
      if (entry.value is! String) {
        throw FormatException('ARB messages must be strings.');
      }
      entries[entry.key] = entry.value as String;
    }
    messages[locale] = entries;
  }
  final bundled = TransLocaleCatalog(
    sourceLocale: sourceLocale,
    file: catalog,
    messages: messages,
  );
  final locales = bundled.supportedLocales.toList()..sort();
  final buffer = StringBuffer(_header)
    ..writeln(
      "import 'package:translocale_dartnative/translocale_dartnative.dart';",
    )
    ..writeln('')
    ..writeln('final translocaleCatalog = TransLocaleCatalog(')
    ..writeln('  sourceLocale: ${_quote(bundled.sourceLocale)},')
    ..writeln('  file: ${_quote(catalog)},')
    ..writeln('  messages: {');
  for (final locale in locales) {
    buffer.writeln('    ${_quote(locale)}: {');
    final keys = bundled.messages[locale]!.keys.toList()..sort();
    for (final key in keys) {
      buffer.writeln(
        '      ${_quote(key)}: ${_quote(bundled.messages[locale]![key]!)},',
      );
    }
    buffer.writeln('    },');
  }
  buffer.writeln('  },\n);');
  final content = buffer.toString();
  final target = File(output);
  final type = FileSystemEntity.typeSync(output, followLinks: false);
  if (type != FileSystemEntityType.notFound &&
      type != FileSystemEntityType.file) {
    throw FileSystemException('Output must be a regular file.', output);
  }
  if (check) {
    if (!target.existsSync() || target.readAsStringSync() != content) {
      throw StateError('Bundle is stale. Regenerate it from the ARB files.');
    }
    return content;
  }
  if (target.existsSync() &&
      (!replace || !target.readAsStringSync().startsWith(_header))) {
    throw StateError(
      'Output exists. Use --replace only for a TransLocale-generated bundle.',
    );
  }
  target.parent.createSync(recursive: true);
  // A temporary sibling prevents a partially written generated Dart file.
  final temporary = File(
    '${target.path}.$pid.${DateTime.now().microsecondsSinceEpoch}.tmp',
  );
  try {
    temporary.writeAsStringSync(content, flush: true);
    temporary.renameSync(target.path);
  } finally {
    if (temporary.existsSync()) temporary.deleteSync();
  }
  return content;
}

const _header =
    '// Generated by translocale_dartnative. Do not edit or format.\n';
