import 'dart:io';
import 'package:args/args.dart';
import 'bundle.dart';

void runBundleCommand(List<String> arguments) {
  final parser = ArgParser()
    ..addOption(
      'arb-dir',
      defaultsTo: 'l10n',
      help: 'Directory containing one ARB file per language.',
    )
    ..addOption('source', defaultsTo: 'en', help: 'Bundled source language.')
    ..addOption(
      'catalog',
      defaultsTo: 'app.arb',
      help: 'Exact catalog identity in TransLocale.',
    )
    ..addOption('out', defaultsTo: 'lib/translocale_bundle.g.dart')
    ..addFlag(
      'check',
      negatable: false,
      help: 'Fail if the existing bundle is stale; write nothing.',
    )
    ..addFlag(
      'replace',
      negatable: false,
      help: 'Replace only a bundle generated by this command.',
    )
    ..addFlag('help', abbr: 'h', negatable: false);
  try {
    final args = parser.parse(arguments);
    if (args.flag('help')) {
      stdout.writeln(parser.usage);
      return;
    }
    if (args.rest.isNotEmpty || (args.flag('check') && args.flag('replace'))) {
      throw ArgumentError(
        'Choose --check or --replace and omit positional arguments.',
      );
    }
    generateBundle(
      directory: args.option('arb-dir')!,
      sourceLocale: args.option('source')!,
      catalog: args.option('catalog')!,
      output: args.option('out')!,
      check: args.flag('check'),
      replace: args.flag('replace'),
    );
    stdout.writeln(
      args.flag('check')
          ? 'Bundle is current.'
          : 'Wrote ${args.option('out')}.',
    );
  } catch (error) {
    stderr.writeln(error);
    exitCode = 1;
  }
}
