// Generated by translocale_dartnative. Do not edit or format.
import 'package:translocale_dartnative/messages.dart';

final translocaleCatalog = TransLocaleCatalog<AppStrings>(
  createMessages: AppStrings._,
  sourceLocale: "en",
  file: "app.arb",
  messages: {
    "ar": {
      "hello": "أهلًا، {name}!",
      "items": "{count, plural, zero {لا ملاحظات} one {ملاحظة واحدة} two {ملاحظتان} few {{count} ملاحظات} many {{count} ملاحظة} other {{count} ملاحظة}}",
      "symbol": "يومياتك",
    },
    "en": {
      "hello": "Hello, {name}!",
      "items": "{count, plural, one {One entry} other {{count} entries}}",
      "symbol": "Your journal",
    },
    "fr": {
      "hello": "Salut, {name} !",
      "items": "{count, plural, one {Une note} other {{count} notes}}",
      "symbol": "Votre journal",
    },
  },
);

final class AppStrings {
  AppStrings._(this._messages);
  final TransLocaleMessageResolver _messages;

  String hello({required String name}) => _messages.resolve(
    "hello",
    arguments: {"name": name},
  );

  String items({required int count}) => _messages.resolve(
    "items",
    arguments: {"count": count},
  );

  String get symbol => _messages.resolve("symbol");
}

