// Generated by translocale_dartnative. Do not edit or format.
import 'package:translocale_dartnative/translocale_dartnative.dart';

final translocaleCatalog = TransLocaleCatalog(
  sourceLocale: "en",
  file: "app.arb",
  messages: {
    "ar": {
      "hello": "أهلًا، {name}!",
      "items": "{count, plural, zero {لا ملاحظات} one {ملاحظة واحدة} two {ملاحظتان} few {{count} ملاحظات} many {{count} ملاحظة} other {{count} ملاحظة}}",
      "symbol": "يومياتك",
    },
    "en": {
      "hello": "Hello, {name}!",
      "items": "{count, plural, one {One entry} other {{count} entries}}",
      "symbol": "Your journal",
    },
    "fr": {
      "hello": "Salut, {name} !",
      "items": "{count, plural, one {Une note} other {{count} notes}}",
      "symbol": "Votre journal",
    },
  },
);
